### ISSUE TITLE
bulk_create does not handle custom attrs correctly

### ISSUE THREAD

**Issue by ryohare** [fortifyadmin/fortifyapi#10]
In ```bulk_create_new_application_version_request```, the custom attributes parameter only allows 1 custom attribute to be specified and only allows for attributes with where the user is to enter data, not those which have selectable options.

A proposed fix would to extend custom_attributes to be an array, consisting of 3 items tuples where idx1=attrId, idx2=values, idx3=value.

**Comment by xolian** [comment]
Thanks for the PR and fix, new pypi v1.0.32 pushed https://pypi.org/project/fortifyapi/

**Comment by ryohare** [comment]
Yup, NP.

One change I may propose down the road, the values parameter to the attributes is actually a list of guids, think multiple check boxes like dev languages. I didn't need it for the change i proposed, but for correctness, may added for those use cases. 

The change could be the values param in the tuple would actually be a list of guids.

**Comment by xolian** [comment]
Are you referring to https://github.com/fortifyadmin/fortifyapi/blob/master/fortifyapi/fortify.py#L91 and the postData list?

**Comment by ryohare** [comment]
Here: https://github.com/fortifyadmin/fortifyapi/blob/master/fortifyapi/fortify.py#L111

The actual rest request takes in:

```json
{  
   "id": "some-attr-id",
   "values":[
       'guid-1',
       'guid-2'
   ],
   "value": null
}
```

So the interface at that the referenced should take a list of guids and construct a json array for the values parameter.

**Comment by xolian** [comment]
Ah gotchya.  Saw that right after I sent the last comment.  Yeah.  I'll add that in this week.
