### ISSUE TITLE
Add/create methods missing?

### ISSUE THREAD

**Issue by fcoene** [fortifyadmin/fortifyapi#12]
Hi,
I am not very experienced at python but I can't seem to find / call the first 3 documented method?
More specifically:
- add_project_version_attribute
- create_project_version
- create_new_project_version
Have they not been implemented yet?
Kind regards

**Comment by xolian** [comment]
Honestly, creating a project version is a more complicated method, but all the api calls are covered in the fortifyapi.  There are approximately, 6 api calls.

First you will need to auth to acquire a token or you can create the token with foritfyclient and use that api token see get_token.  Create your methods like so...

```
response = FortifyApi(host=self.config.ssc_url, username=self.username, password=self.password, verify_ssl=self.config.verify_ssl, timeout=self.config.timeout)
return response
```
Then use that API Token like so...

```
response = FortifyApi(self.config.ssc_url, token=token, verify_ssl=self.config.verify_ssl,
                                  timeout=self.config.timeout)
return response
```
You can create other methods other methods you will need to implement include, create_application_version, bulk_create_new_application_version_request, set_processing_rules, and get_attribute_definition.

**Comment by xolian** [comment]
@fcoene Tell you what... I am going to add a new Object class that you can use to create and list Application/Project Versions.

**Comment by fcoene** [comment]
That sounds great. I find the SSC REST API really difficult to work with. Making abstraction of those difficult API calls and working with objects just makes a lot more sense when you want to implement some integration/automation. I had just managed to create basic applications after several hours of studying and experimenting with your code. The fact that the attribute_definition numbers for the development_phase, development_strategy, accessibility and business_risk_ranking are different on our SSC server (in the 4000 range) made it even more difficult. I was also thinking of some maintenance functionality like deleting an application/version by name (which is not possible with the API) and purging application/versions (deleting all artifacts older than X days). Maybe I will manage to contribute some code.

**Comment by xolian** [comment]
cool.  glad you figured it out, unfortunately APIs are always quirky.  I have done pretty much everything you can imagine with the Fortify SSC API, so if you need any help ?  Feel free to contact me.  Also, if you are using basic auth to create the UnifiedAccessToken remember to introduce a function to delete them.  You can't go greater than 200 tokens in SSC.
