### ISSUE TITLE
SSC 21.1.1

### ISSUE THREAD

**Issue by oaldahir** [fortifyadmin/fortifyapi#18]
get_projects and get_all_project_version not working with ssc 21.1.1

TypeError: 'NoneType' object is not subscriptable
There was an error while handling the request. 400 Client Error:  for url: https://fortify:8443/ssc/api/v1/projects?start=-1&limit=-1

**Comment by xolian** [comment]
Thank you for opening up this ticket.  I'll start some testing on v21.1.1.  We should have a new version avail by Friday.

**Comment by xolian** [comment]
Have you applied the Fortify Software Security Center Patch 21.1.2?

**Comment by oaldahir** [comment]
I have not. I will try. Patch notes say nothing about API tho.

**Comment by xolian** [comment]
Pagination query limits on the endpoints need to be changed.  I'll have a fix for you tomorrow that will work on v21, need to test on also v20 too

**Comment by xolian** [comment]
Merging `bugfix/querylimits-v2112` branch for fix.  Modified start values to 0 for pagination.

**Comment by oaldahir** [comment]
Hi Brandon,

I upgraded to FortifyAPI 2.5 and I’m using SSC 21.1.2 and still get the same error for:

def list():
    print(token())
    response = api().get_projects()
    print(response)
    data = response.data['data']


if __name__ == '__main__':
    list()

There was an error while handling the request. 400 Client Error:  for url: https://myip:8443/ssc:8443/ssc/api/v1/projects?start=-1&limit=-1
Traceback (most recent call last):
  File "/home/user/PycharmProjects/pythonProject/ssc.py", line 41, in <module>
    list()
  File "/home/user/PycharmProjects/pythonProject/ssc.py", line 37, in list
    data = response.data['data']
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1


I don’t get an error when I run:


def list():
    print(token())
    response = api().get_all_issue_aging()
    print(response)
    data = response.data['data']


if __name__ == '__main__':
    list()

/home/user/Projects/pythonProject/venv/bin/python /home/user/PycharmProjects/pythonProject/ssc.py
ZDA2YmI1MGEtMTU2MS00NDllLWJlYTYtMGYwNTgyMmY2ZTE4
{'data': {'issuesRemediated': 811, 'issuesPendingReview': 6485, 'openIssues': 8185, 'openIssuesReviewed': 1700, 'averageDaysToReview': 92, 'averageDaysToRemediate': 126, 'applicationVersions': 14, 'linesOfCode': 382852, 'filesScanned': 6735}, 'responseCode': 200}

Process finished with exit code 0


***@***.***:~$ pip install fortifyapi
Collecting fortifyapi
  Using cached fortifyapi-2.5-py3-none-any.whl (12 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from fortifyapi) (2.22.0)
Requirement already satisfied: pandas in ./.local/lib/python3.8/site-packages (from fortifyapi) (1.1.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/lib/python3/dist-packages (from pandas->fortifyapi) (2.7.3)
Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3/dist-packages (from pandas->fortifyapi) (2019.3)
Requirement already satisfied: numpy>=1.15.4 in ./.local/lib/python3.8/site-packages (from pandas->fortifyapi) (1.19.1)
Installing collected packages: fortifyapi
Successfully installed fortifyapi-2.5

Thanks

**Comment by oaldahir** [comment]
Hi Brian. Sorry for the confusion. I am still experiencing the same issue/error when I try to run api().get_projects().
