### ISSUE TITLE
No compatibility with Python < 3.8

### ISSUE THREAD

**Issue by theoricien** [fortifyadmin/fortifyapi#26]
Because fortifyapi is using the ":=" Python operator, users with Python < 3.8 can't use the module

**Comment by xolian** [comment]
@theoricien this operator is not used in the current release of fortifyapi, See also `fortifyapi/fortify.py` and should be compatible.  However, this operator has been staged for a future release, but is currently not avail.

**Comment by xolian** [comment]
@theoricien Thank you for opening up this issue.  However, where in `fortifyapi/fortify.py` do you see the use of the operator?  This is the only file that is currently in use for the current release.

**Comment by vetsin** [comment]
does it try to compile https://github.com/fortifyadmin/fortifyapi/blob/master/fortifyapi/client.py#L155?

either way we don't need to use the operator

**Comment by xolian** [comment]
@theoricien confirmed the `client.py` is included in the whl  distro.  Staging fix on scratch/exclude_files branch

**Comment by ferricoxide** [comment]
Glad I'm not the only one hitting this (I'm in an EL7 environment and stuck with Python 3.6.8 for the time being). At any rate, "following".

**Comment by xolian** [comment]
Published fortifyapi v3.0.6. the client.py is part of future refactoring of the lib.  Will use lambdas instead of walrus operator in near future for backwards compatibility with py v3.8 and earlier.  @ferricoxide and @theoricien please confirm this is fixed on your end?

**Comment by ferricoxide** [comment]
> &hellip; @ferricoxide and @theoricien please confirm this is fixed on your end?

I'll have to spin a copy of the container (to inject our internal CAs), first. I'll try to put that on my punch-list for this week.

**Comment by ferricoxide** [comment]
Ok. Can't specifically remember how I triggered the issue to get here. I remember it was pretty early on in the "checking things out to see if this module will be useful for me". That said, `pip install …` and attempting to `import` the module both appear to work without the error being logged.

**Comment by xolian** [comment]
@ferricoxide thanks for testing it.  I am closing this out.
