### ISSUE TITLE
Is fortifyapi itself scanned by fortify ?

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [fortifyadmin/fortifyapi#51]
Hi,

I am wondering, is there any fortify scan ran on fortifyapi itself ? I tried to look in what I think is your CI configuration (https://github.com/fortifyadmin/fortifyapi/blob/master/.circleci/config.yml) and I didn't see any scan being started. But most likely I am looking at the wrong place ;)

Cheers,
Romain

**Comment by xolian** [comment]
we are not running fortify scans from our pipeline, that service is not publicly available.

**Comment by Romain-Geissler-1A** [comment]
Ok thanks for the reply.
